---
- name: Install and configure NGINX
  hosts: nginx
  become: true
  vars:
    nginx_listen_port: 8080
  tasks:
    - name: Install EPEL Repo package from standart repo
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: Install NGINX package from epel-repo
      yum:
        name: nginx
        state: latest
      tags:
        - nginx-package
        - packages

    - name: Create NGINX config file from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      tags:
        - nginx-configuration
