gunicorn:
    image: gunicorn
    container_name: gunicorn
    ports:
      - 8000:8000
    volumes:
      - ./app:/app

nginx:
    image: "nginx:1.13-alpine"
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - gunicorn

    